The Pin imports for MCP2221 was missing from the module and thus you would get the following error when using certain libraries.
NotImplementedError: ('Microcontroller not supported:', 'MCP2221')