update minimum version of Adafruit-PlatformDetect
Needed since 8273fc6, otherwise you will get:

```
AttributeError: module 'adafruit_platformdetect.constants.chips' has no attribute 'DRA74X'
```